# Generated by Django 3.2.12 on 2022-11-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20221108_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publishedDate',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
